server:
  port: 3000

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: LOCATIONSERVICE
          uri: http://localhost:3001
          predicates:
            - Path=/trackers/**